name: Generate merge-ut-dictionaries artifact

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout merge-ut-dictionaries
        uses: actions/checkout@v7

      - name: Run make.sh in src/merge/
        working-directory: ./src/merge
        run: |
          chmod +x make.sh
          sh make.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: merge-ut-dictionaries-artifact
          path: ./src/merge/mozcdic-ut.txt
          retention-days: 1
